[world]
description = "jokers_of_neon_classic"
name = "jokers_of_neon_classic"
seed = "jokers_of_neon_classic"

[namespace]
default = "jokers_of_neon_classic"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x6677fe62ee39c7b07401f754138502bab7fac99d2d3c5d37df7d1c6fab10819"
private_key = "0x3e3979c1ed728490308054fe357a9f49cf67f80f9721f44cc57235129e090f4"

[writers]
"jokers_of_neon_classic" = [
"jokers_of_neon_classic-registrator_system",
    "jokers_of_neon_classic-special_multi_for_heart",
    "jokers_of_neon_classic-special_multi_for_club",
    "jokers_of_neon_classic-special_multi_for_diamond",
    "jokers_of_neon_classic-special_multi_for_spade",
    "jokers_of_neon_classic-special_increase_level_pair",
    "jokers_of_neon_classic-special_increase_level_double_pair",
    "jokers_of_neon_classic-special_increase_level_straight",
    "jokers_of_neon_classic-special_increase_level_flush",
    "jokers_of_neon_classic-special_straight_with_four_cards",
    "jokers_of_neon_classic-special_flush_with_four_cards",
    "jokers_of_neon_classic-special_joker_booster",
    "jokers_of_neon_classic-special_power_up_booster",
    "jokers_of_neon_classic-special_points_for_figures",
    "jokers_of_neon_classic-special_multi_aces",
    "jokers_of_neon_classic-special_all_cards_to_hearts",
    "jokers_of_neon_classic-special_hand_thief",
    "jokers_of_neon_classic-special_extra_help",
    "jokers_of_neon_classic-special_lucky_seven",
    "jokers_of_neon_classic-special_neon_bonus",
    "jokers_of_neon_classic-special_initial_advantage",
    "jokers_of_neon_classic-special_lucky_hand",
    "jokers_of_neon_classic-special_discard_mastery",
    "jokers_of_neon_classic-special_neon_synergy",
    "jokers_of_neon_classic-special_retired_joker",
    "jokers_of_neon_classic-special_idle_joker",
    "jokers_of_neon_classic-special_life_saver",
    "jokers_of_neon_classic-special_pack_discount",
    "jokers_of_neon_classic-special_plus_discards",
    "jokers_of_neon_classic-special_plus_plays",
    "jokers_of_neon_classic-special_increase_level_full_house",
    "jokers_of_neon_classic-special_increase_level_three_of_a_kind",
    "jokers_of_neon_classic-special_increase_level_four_of_a_kind",
    "jokers_of_neon_classic-special_increase_level_five_of_a_kind",
    "jokers_of_neon_classic-special_random_multi_for_heart",
    "jokers_of_neon_classic-special_random_multi_for_club",
    "jokers_of_neon_classic-special_random_multi_for_diamond",
    "jokers_of_neon_classic-special_random_multi_for_spade"
]
